services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: 8080
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_SERVER_PORT: 8088
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: never
    expose:
      - "8088"       # ← 컨테이너 간 통신만 필요하면 expose만
    # ports:
    #   - "8080:8080" # 호스트로도 열고 싶을 때만
    # 로컬에서 compose 실행시 .env 파일이 로컬에 선언되어야 함

  certgen:
    image: alpine:3.20
    volumes:
      - ./certs:/out:rw
    command: >
      sh -c "
      apk add --no-cache openssl >/dev/null 2>&1;
      [ -f /out/dev.key ] || openssl req -x509 -newkey rsa:2048 -nodes -days 825
      -subj '/CN=dev-naver.i4624.info'
      -addext 'subjectAltName=DNS:dev-naver.i4624.info,DNS:s3storage.i4624.info,IP:127.0.0.1'
      -keyout /out/dev.key -out /out/dev.crt
      "

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      certgen:
        condition: service_completed_successfully
      app:
        condition: service_started
    ports:
      - "446:443"
      - "42777:42777"
    volumes:
      - ./certs:/etc/ssl/local:ro
    command: ["nginx", "-g", "daemon off;"]
