spring:
  application:
    name: s3object
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

ceph:
  s3:
    endpoint: https://s3storage.i4624.info
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: us
    bucket: images

server:
  port: 8088